# Generated by Django 4.0.2 on 2022-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('displayName', models.TextField()),
                ('base', models.TextField()),
                ('quote', models.TextField()),
            ],
        ),
    ]
