# Generated by Django 4.0.2 on 2022-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
