# Generated by Django 4.0.2 on 2022-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTrade', '0003_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='penetration',
            field=models.BooleanField(default=False),
        ),
    ]
